### PR TITLE
Added ward map

### PR DESCRIPTION
**Pull request by MaxWorgan**

### CODE REVIEW

**Comment by MaxWorgan** [comment]
@robdyke :eyes:

**Comment by robdyke** [comment]
Working on e2e with openeobs/openeobs-docker

**Comment by robdyke** [comment]
```
mvn -version
Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 10.0.2, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-20-generic", arch: "amd64", family: "unix"
```

```
java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
```
```
robd@rd-nuc:~/Work/neovahealth/adt-connector/docker$ registry=openeobs make all
```

**Comment by robdyke** [comment]
[RTFM](https://www.scala-lang.org/download/). "First, make sure you have the Java 8 JDK installed."

```sh
sudo apt install openjdk-8-jdk
sudo update-alternatives --config java
```

**Comment by robdyke** [comment]
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.562 s - in uk.co.neovahealth.nhADT.ADTGenTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:47 min
[INFO] Finished at: 2018-12-26T23:49:07Z
[INFO] Final Memory: 29M/496M
[INFO] ------------------------------------------------------------------------
```

**Comment by robdyke** [comment]
@MaxWorgan Looking good. Will hook up to a working open-eObs instance tmrw for further testing.

**Comment by robdyke** [comment]
@MaxWorgan https://travis-ci.com/NeovaHealth/adt-connector/builds/96008052

**Comment by robdyke** [comment]
@MaxWorgan :eyes: 

`⇒` is not `=>`

**Comment by robdyke** [comment]
@MaxWorgan Green = Good

**Comment by robdyke** [comment]
Closes #4

**Pull request merged**
